#!/usr/bin/python3

from sqlalchemy import Table, Column, ForeignKey, String
from sqlalchemy.orm import relationship
from models.base_model import Base

# Define the association table for many-to-many relationship
place_amenity = Table('place_amenity', Base.metadata,
    Column('place_id', String(60), ForeignKey('places.id'), primary_key=True),
    Column('amenity_id', String(60), ForeignKey('amenities.id'), primary_key=True)
)
